config/routes.rb
ContaktDemo::Application.routes.draw do

  resources :emails

  resources :faxes

  resources :phones

  resources :addresses, :only => [:destroy, :new, :create, :edit, :update] do
    post :thank_you, :on => :collection
  end
  resources :configurations, :only => [:edit, :update]
  
  root :to => "home#index"
  
  get '/:name' => 'addresses#index'
  get '/:name/address/:id' => 'addresses#show'
  post '/:name/thank_you' => 'addresses#thank_you'
  get '/home/dashboard' => 'home#show'
  get 'addresses#index' => "home#index"
  
  get '/addresses/subregion_options' => 'addresses#subregion_options'
  
  devise_for :users, skip: :registrations, path_names: { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'register' },
      controller: 'devise/registrations',
      as: :user_registration do
      get :cancel
    end
  end
  
  
  resources :home do
    get :careers, :on => :collection
    get :product, :on => :collection
    get :about_us, :on => :collection
    get :faqs, :on => :collection
    get :contact_us, :on => :collection
    get :foo, :on => :collection
  end
  
  match "about_us" => "home#about_us"
  match "careers" => "home#careers"
  match "product" => "home#product"
  match "faqs" => "home#faqs"
  match "contact_us" => "home#contact_us"

end

app/models/phone.rb
class Phone < ActiveRecord::Base
  attr_accessible :address_id, :label, :number
  
  validates_format_of :number, with: /^\d{10,15}$/i, :allow_blank => true
  
  belongs_to :address
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  # GET /phones
  # GET /phones.json
  def index
    @phones = Phone.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @phones }
    end
  end

  # GET /phones/1
  # GET /phones/1.json
  def show
    @phone = Phone.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @phone }
    end
  end

  # GET /phones/new
  # GET /phones/new.json
  def new
    @phone = Phone.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @phone }
    end
  end

  # GET /phones/1/edit
  def edit
    @phone = Phone.find(params[:id])
  end

  # POST /phones
  # POST /phones.json
  def create
    @phone = Phone.new(params[:phone])

    respond_to do |format|
      if @phone.save
        format.html { redirect_to @phone, notice: 'Phone was successfully created.' }
        format.json { render json: @phone, status: :created, location: @phone }
      else
        format.html { render action: "new" }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /phones/1
  # PUT /phones/1.json
  def update
    @phone = Phone.find(params[:id])

    respond_to do |format|
      if @phone.update_attributes(params[:phone])
        format.html { redirect_to @phone, notice: 'Phone was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1
  # DELETE /phones/1.json
  def destroy
    @phone = Phone.find(params[:id])
    @phone.destroy

    respond_to do |format|
      format.html { redirect_to phones_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/phones/_form.html.erb
<%= form_for(@phone) do |f| %>
  <% if @phone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phone.errors.count, "error") %> prohibited this phone from being saved:</h2>

      <ul>
      <% @phone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phones/edit.html.erb
<h1>Editing phone</h1>

<%= render 'form' %>

<%= link_to 'Show', @phone %> |
<%= link_to 'Back', phones_path %>

app/views/phones/index.html.erb
<h1>Listing phones</h1>

<table>
  <tr>
    <th>Label</th>
    <th>Number</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @phones.each do |phone| %>
  <tr>
    <td><%= phone.label %></td>
    <td><%= phone.number %></td>
    <td><%= phone.address_id %></td>
    <td><%= link_to 'Show', phone %></td>
    <td><%= link_to 'Edit', edit_phone_path(phone) %></td>
    <td><%= link_to 'Destroy', phone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Phone', new_phone_path %>

app/views/phones/new.html.erb
<h1>New phone</h1>

<%= render 'form' %>

<%= link_to 'Back', phones_path %>

app/views/phones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Label:</b>
  <%= @phone.label %>
</p>

<p>
  <b>Number:</b>
  <%= @phone.number %>
</p>

<p>
  <b>Address:</b>
  <%= @phone.address_id %>
</p>


<%= link_to 'Edit', edit_phone_path(@phone) %> |
<%= link_to 'Back', phones_path %>