config/routes.rb
ContaktDemo::Application.routes.draw do

  resources :emails

  resources :faxes

  resources :phones

  resources :addresses, :only => [:destroy, :new, :create, :edit, :update] do
    post :thank_you, :on => :collection
  end
  resources :configurations, :only => [:edit, :update]
  
  root :to => "home#index"
  
  get '/:name' => 'addresses#index'
  get '/:name/address/:id' => 'addresses#show'
  post '/:name/thank_you' => 'addresses#thank_you'
  get '/home/dashboard' => 'home#show'
  get 'addresses#index' => "home#index"
  
  get '/addresses/subregion_options' => 'addresses#subregion_options'
  
  devise_for :users, skip: :registrations, path_names: { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'register' },
      controller: 'devise/registrations',
      as: :user_registration do
      get :cancel
    end
  end
  
  
  resources :home do
    get :careers, :on => :collection
    get :product, :on => :collection
    get :about_us, :on => :collection
    get :faqs, :on => :collection
    get :contact_us, :on => :collection
    get :foo, :on => :collection
  end
  
  match "about_us" => "home#about_us"
  match "careers" => "home#careers"
  match "product" => "home#product"
  match "faqs" => "home#faqs"
  match "contact_us" => "home#contact_us"

end

app/models/fax.rb
class Fax < ActiveRecord::Base
  attr_accessible :address_id, :label, :number
  validates_format_of :number, with: /^\d{10,15}$/i, :allow_blank => true
  
  belongs_to :address
end

app/controllers/faxes_controller.rb
class FaxesController < ApplicationController
  # GET /faxes
  # GET /faxes.json
  def index
    @faxes = Fax.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @faxes }
    end
  end

  # GET /faxes/1
  # GET /faxes/1.json
  def show
    @faxis = Fax.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @faxis }
    end
  end

  # GET /faxes/new
  # GET /faxes/new.json
  def new
    @faxis = Fax.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @faxis }
    end
  end

  # GET /faxes/1/edit
  def edit
    @faxis = Fax.find(params[:id])
  end

  # POST /faxes
  # POST /faxes.json
  def create
    @faxis = Fax.new(params[:faxis])

    respond_to do |format|
      if @faxis.save
        format.html { redirect_to @faxis, notice: 'Fax was successfully created.' }
        format.json { render json: @faxis, status: :created, location: @faxis }
      else
        format.html { render action: "new" }
        format.json { render json: @faxis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /faxes/1
  # PUT /faxes/1.json
  def update
    @faxis = Fax.find(params[:id])

    respond_to do |format|
      if @faxis.update_attributes(params[:faxis])
        format.html { redirect_to @faxis, notice: 'Fax was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @faxis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faxes/1
  # DELETE /faxes/1.json
  def destroy
    @faxis = Fax.find(params[:id])
    @faxis.destroy

    respond_to do |format|
      format.html { redirect_to faxes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/faxes_helper.rb
module FaxesHelper
end

app/views/faxes/_form.html.erb
<%= form_for(@faxis) do |f| %>
  <% if @faxis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faxis.errors.count, "error") %> prohibited this faxis from being saved:</h2>

      <ul>
      <% @faxis.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :address_id %><br />
    <%= f.number_field :address_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/faxes/edit.html.erb
<h1>Editing faxis</h1>

<%= render 'form' %>

<%= link_to 'Show', @faxis %> |
<%= link_to 'Back', faxes_path %>

app/views/faxes/index.html.erb
<h1>Listing faxes</h1>

<table>
  <tr>
    <th>Label</th>
    <th>Number</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @faxes.each do |faxis| %>
  <tr>
    <td><%= faxis.label %></td>
    <td><%= faxis.number %></td>
    <td><%= faxis.address_id %></td>
    <td><%= link_to 'Show', faxis %></td>
    <td><%= link_to 'Edit', edit_faxis_path(faxis) %></td>
    <td><%= link_to 'Destroy', faxis, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fax', new_faxis_path %>

app/views/faxes/new.html.erb
<h1>New faxis</h1>

<%= render 'form' %>

<%= link_to 'Back', faxes_path %>

app/views/faxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Label:</b>
  <%= @faxis.label %>
</p>

<p>
  <b>Number:</b>
  <%= @faxis.number %>
</p>

<p>
  <b>Address:</b>
  <%= @faxis.address_id %>
</p>


<%= link_to 'Edit', edit_faxis_path(@faxis) %> |
<%= link_to 'Back', faxes_path %>