config/routes.rb
ContaktDemo::Application.routes.draw do

  resources :emails

  resources :faxes

  resources :phones

  resources :addresses, :only => [:destroy, :new, :create, :edit, :update] do
    post :thank_you, :on => :collection
  end
  resources :configurations, :only => [:edit, :update]
  
  root :to => "home#index"
  
  get '/:name' => 'addresses#index'
  get '/:name/address/:id' => 'addresses#show'
  post '/:name/thank_you' => 'addresses#thank_you'
  get '/home/dashboard' => 'home#show'
  get 'addresses#index' => "home#index"
  
  get '/addresses/subregion_options' => 'addresses#subregion_options'
  
  devise_for :users, skip: :registrations, path_names: { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'register' },
      controller: 'devise/registrations',
      as: :user_registration do
      get :cancel
    end
  end
  
  
  resources :home do
    get :careers, :on => :collection
    get :product, :on => :collection
    get :about_us, :on => :collection
    get :faqs, :on => :collection
    get :contact_us, :on => :collection
    get :foo, :on => :collection
  end
  
  match "about_us" => "home#about_us"
  match "careers" => "home#careers"
  match "product" => "home#product"
  match "faqs" => "home#faqs"
  match "contact_us" => "home#contact_us"

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show, :thank_you]
  before_filter :find_user_addresses, :only => [:index, :show, :thank_you]
  
  # GET /addresses
  # GET /addresses.json
  def index
    @form = Form.new(params[:form]) 
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @addresses }
    end
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
    id = params[:id].to_i - 1
    if (id < 0) or (id > @addresses.length)
      respond_to do |format|
        format.html { redirect_to "/#{@user.name}", alert: 'Address was not found.'}
        format.json { render json: @address }
      end
    else
      @address = @addresses[id]
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @address }
      end
    end
    
  end

  # GET /addresses/new
  # GET /addresses/new.json
  def new
    @address = current_user.addresses.new
    @address.phones.build
    @address.faxs.build
    @address.emails.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/1/edit
  def edit
    @address = current_user.addresses.find(params[:id])
    @address.phones.build
    @address.faxs.build
    @address.emails.build
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = current_user.addresses.new(params[:address])
    @count = current_user.addresses.count
    respond_to do |format|
      if @address.save
        format.html { redirect_to "/#{current_user.name}/address/#{@count + 1}", notice: 'Address was successfully created.' }
        format.json { render json: @address, status: :created, location: @address }
        format.js
      else
        @address.phones.build
        @address.faxs.build
        @address.emails.build
        format.html { render action: "new" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
        format.js 
      end
    end
  end

  # PUT /addresses/1
  # PUT /addresses/1.json
  def update
    @address = current_user.addresses.find(params[:id])
    respond_to do |format|
      if @address.update_attributes(params[:address])
        format.html { redirect_to "/#{current_user.name}", notice: 'Address was successfully updated.' }
        format.json { head :no_content }
      else
        @address.phones.build
        @address.faxs.build
        @address.emails.build
        format.html { render action: "edit" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address = current_user.addresses.find(params[:id])
    @address.destroy

    respond_to do |format|
      format.html { redirect_to addresses_url }
      format.json { head :no_content }
      format.js { render :js => "$(this).parent().parent().remove(); this.preventDefault();" } 
    end
  end
  
  
  # POST /thank_you
  def thank_you
    @form = Form.new(params[:form])
    respond_to do |format|
      if @form.save
        format.html { redirect_to("/#{@user.name}", :notice => 'Thanks for contacting us.') }
      else
        params[:name] = @user.name
        format.html { render action: "index"}
      end
    end
  end
  
  def subregion_options
    render partial: 'subregion_select'
  end
  
  
  
  private
  
  def find_user_addresses
    unless params[:name].blank?
      @user = User.find_by_name(params[:name])
      @addresses = @user.addresses unless @user.blank?
      if @user.blank?
        respond_to do |format|
          format.html { redirect_to root_url }# index.html.erb
          format.json { head :no_content }
        end
      end
    end
  end
  
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_contact_form.html.erb
<div class="well">
  <h2>Contact Form </h2>
  <hr>
  <br>

  <%= form_for @form, :url => "/#{@user.name}/thank_you", :html => { :class => 'form-horizontal' } do |f| %>
  
    <% unless @form.errors.blank? %>
    <div class="alert alert-error">
      <% @form.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
      <% end %>
    </div>
    <% end %>
  
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field', :placeholder => "Enter your full name" %>
      </div>
    </div>
  
    <div class="control-group">
      <%= f.label :mobile, :class => 'control-label' %>
      <div class="controls">
        <div class="input-prepend">
          <span class="add-on">+</span>
          <%= f.text_field :mobile, :class => 'text_field span8', :placeholder => "Mobile Number", :size => 39 %>
        </div>    
      </div>
    </div>
  
    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_field', :placeholder => "Email Address" %>
      </div>
    </div>
  
  
    <div class="control-group">
      <%= f.label :message, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :message, :class => 'text_area', :placeholder => "Enter your message", :rows => 4 %>
      </div>
    </div>
  
    <%= f.hidden_field :user_id, :class => 'text_field', :value => @user.id %>
  
    <div class="control-group">
      <div class="controls">
        <%= f.submit "Submit", :class => "btn-large btn-primary" %>
      </div>
    </div>
  <% end %>

</div>

app/views/addresses/_email_fields.html.erb
<span class="nested-fields"> 
  <br><br>
  <%= f.text_field :email, :class => 'text_field span8', :placeholder => "Email Address"%>
  <%= link_to_remove_association "-", f, :class => "btn btn-danger" %>
</span>

app/views/addresses/_fax_fields.html.erb
<span class="nested-fields"> 
  <br><br>
  <div class="input-prepend">
    <span class="add-on">+</span>
    <%= f.text_field :number, :class => 'text_field span10', :placeholder => "Fax number" %>
  </div>
  <%= link_to_remove_association "-", f, :class => "btn btn-danger" %>
</span>

app/views/addresses/_form.html.erb
<div id="map_canvas" style="width:40%; height:400px; margin: 10px; background-color: #fff;" class="well pull-left">
</div>
<div class="pull-left" style="width:50%">
  <%= form_for @address, :html => { :class => 'form-horizontal' } do |f| %>

    <% unless @address.errors.blank? %>
    <div class="alert alert-error">
      <% @address.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
      <% end %>
    </div>
    <% end %>
  
    <div class="control-group">
      <%= f.label "Heading", :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :label, :class => 'text_field', :placeholder => "Headquarter, Sales off. etc" %>
      </div>
    </div>
    
     <div class="control-group">
         <%= f.label :country, :class => 'control-label' %>
         <div class="controls">
           <%= f.country_select :country, priority: %w(US IN), prompt: 'Please select a country' %>
         </div>
       </div>

       <div class="control-group">
         <%= f.label :state, :class => 'control-label' %>
         <div class="controls">
           <%= render partial: 'subregion_select', locals: {parent_region: f.object.country} %>
         </div>
       </div>

      <div class="control-group">
        <%= f.label :city, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :city, :class => 'text_field' %>
        </div>
      </div>
  
    <div class="control-group">
      <%= f.label :street_address, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :street_address, :class => 'text_field' %>
      </div>
    </div>
  
    <div class="control-group">
      <%= f.label "street_address_two", :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :street_address_two, :class => 'text_field' %>
      </div>
    </div>
  
    <div class="control-group">
      <%= f.label :zipcode, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :zipcode, :class => 'text_field' %>
      </div>
    </div>
    
    <%= f.hidden_field :latitude, :class => 'hidden_field' %>
    
    <%= f.hidden_field :longitude, :class => 'hidden_field' %>
    
  
    <div class="control-group">
      <%= f.label "Phone Number", :class => 'control-label' %>
      <div class="controls">
        <%= f.fields_for :phones do |phone| %>
        <div class="input-prepend">
          <span class="add-on">+</span>
          <%= phone.text_field :number, :class => 'span10', :placeholder => "Phone number" %>
        </div>
        <% end %>
        <span><%= link_to_add_association '+', f, :phones, :class => "btn btn-info" %></span>
      </div>
    </div>
  
    <div class="control-group">
      <%= f.label "Fax Number", :class => 'control-label' %>
      <div class="controls">
        <%= f.fields_for :faxs do |fax| %>
        <div class="input-prepend">
          <span class="add-on">+</span>
          <%= fax.text_field :number, :class => 'span10', :placeholder => "Fax number"%>
        </div>
        <% end %>
        <span><%= link_to_add_association '+', f, :faxs, :class => "btn btn-info" %></span>
      </div>
    </div>
  
      <div class="control-group">
        <%= f.label :email, :class => 'control-label' %>
        <div class="controls">
          <%= f.fields_for :emails do |email| %>
            <%= email.text_field :email, :class => 'text_field span8', :placeholder => "Email Address"%>
          <% end %>
          <span>&nbsp;&nbsp;<%= link_to_add_association '+', f, :emails, :class => "btn btn-info" %></span>
        </div>
      </div>
  

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary', :data => {:disable_with => "Saving..."} %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  addresses_path, :class => 'btn' %>
    </div>
  <% end %>
</div>

<div class="clearfix"></div>

<script type="text/javascript">
  var geocoder;
  var map;
  var markersArray = [];
  //var marker;
  
  function setLatitudeLongitude(location){
    $("#address_latitude").val(location.Ya);
    $("#address_longitude").val(location.Za);
  }
  
</script>

<script>
  function initialize() {
    geocoder = new google.maps.Geocoder();
    var zoom_level;
    if (<%= @address.latitude.blank? %> || <%= @address.longitude.blank? %>) {
      var myLatlng = new google.maps.LatLng(<%= @address.default_coordinates[0] %>, <%= @address.default_coordinates[1] %>) ;
      zoom_level = 3;
    }
    else {
      var myLatlng = new google.maps.LatLng(<%= @address.latitude.to_f %>, <%= @address.longitude.to_f %>) ;
      zoom_level = 15;
      clearOverlays();
    }
    var mapOptions = {
      center: myLatlng,
      zoom: zoom_level,
      mapTypeId: google.maps.MapTypeId.ROADMAP,
    };
    
    map = new google.maps.Map(document.getElementById("map_canvas"),
        mapOptions);  
    addMarker(myLatlng);
          
 }
 
 function codeAddress(address, zoom) {
   var address = address;
   geocoder.geocode( { 'address': address}, function(results, status) {
     if (status == google.maps.GeocoderStatus.OK) {
       map.setZoom(zoom);
       map.setCenter(results[0].geometry.location);
       clearOverlays();
       addMarker(results[0].geometry.location);
       setLatitudeLongitude(results[0].geometry.location);
     } else {
       alert("Address not found for the following reason: " + status);
     }
   });
 }
 
 
   function addMarker(location) {
     console.log(location);
     var marker = new google.maps.Marker({
       position: location,
       map: map,
       draggable: true,
       animation: google.maps.Animation.DROP,
     });
     markersArray.push(marker);
     google.maps.event.addListener(marker, 'dragend', function() {
         latLong = marker.getPosition();
         setLatitudeLongitude(latLong);
       });
     marker.setMap(map);
   }

   // Removes the overlays from the map, but keeps them in the array
   function clearOverlays() {
     if (markersArray) {
       for (i in markersArray) {
         markersArray[i].setMap(null);
       }
     }
   }

   // Shows any overlays currently in the array
   function showOverlays() {
     if (markersArray) {
       for (i in markersArray) {
         markersArray[i].setMap(map);
       }
     }
   }

   // Deletes all markers in the array by removing references to them
   function deleteOverlays() {
     if (markersArray) {
       for (i in markersArray) {
         markersArray[i].setMap(null);
       }
       markersArray.length = 0;
     }
   }
 
  function loadScript() {
   var script = document.createElement("script");
   script.type = "text/javascript";
   script.src = "http://maps.googleapis.com/maps/api/js?key=AIzaSyAiWC6EU28mQk9du90WHXUQTSTaE48FlFw&libraries=places&sensor=false&callback=initialize";
   document.body.appendChild(script);
  }

  window.onload = loadScript;
</script>

<script>
  
  $("#address_country").live('change', function(){
    updateAddress(5);
  });
  
  $("#address_state").live('change', function(){
    updateAddress(7);
  });

  $("#address_city").live('change', function(){
    updateAddress(10);
  });
  
  $("#address_street_address").live('change', function(){
    updateAddress(13);
  });
  
  $("#address_street_address_two").live('change', function(){
    updateAddress(15)
  });
  
  function updateAddress(zoom){
    var address = "";
    var state = $("#address_state").val();
    var country = $("#address_country").val();
    var city = $("#address_city").val();
    var street = $("#address_street_address").val();
    var street2 = $("#address_street_address_two").val();
    if (street) { address = street + ", " ;}
    if (street2) { address += street2 + ", " ;}
    if (city) { address += city + ", " ;}
    if (state) { address += state + ", " ;}
    if (country) { address += country;}
    codeAddress(address, zoom);
  }
</script>

app/views/addresses/_phone_fields.html.erb
<span class="nested-fields"> 
  <br><br>
  <div class="input-prepend">
    <span class="add-on">+</span>
    <%= f.text_field :number, :class => 'text_field span10', :placeholder => "Phone number" %>
  </div>
  <%= link_to_remove_association "-", f, :class => "btn btn-danger" %>
</span>

app/views/addresses/_subregion_select.html.erb
<div id="order_state_code_wrapper">
  <% parent_region ||= params[:parent_region] %>
  <% country = Carmen::Country.coded(parent_region) %>

  <% if country.nil? %>
    <em>Please select a country above</em>
  <% elsif country.subregions? %>
    <%= subregion_select(:address, :state, parent_region) %>
  <% else %>
    <%= text_field(:address, :state) %>
  <% end %>
</div>

app/views/addresses/edit.html.erb
<%- model_class = Address -%>
<div class="page-header">
  <h1>Modify Location<%#=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/addresses/index.html.erb
<%- model_class = Address -%>
<div class="page-header">
  <h1><%= "#{@user.company_name} " %><small><%= link_to "(#{@user.company_url})", @user.company_url, :target => "_blank" %></small></h1>
</div>
<h4>Address Locations</h4>
<br>

<% if user_signed_in? %>
  <% if @addresses.empty? and can? :create, current_user.addresses.new %>
    <p>You have no locations added to your profile. Please <%= link_to "Add new location", new_address_path, class: "btn-warning btn-large"%></p>
  <% end %>
<% elsif @addresses.empty? %>
  <p><%= "#{@user.company_name}" %> have not added locations yet to their account</p>
<% end %>

<% if !@addresses.empty? %>
  <% @addresses.each_with_index do |address, index| %>
  <div class="address well well-large span4" style="cursor:pointer;">
    <span style="float:right;">
    
      <% if can? :update, address %>
        <%= link_to (image_tag("/assets/edit_tool.png", :width => "15", :height => "20")),
        edit_address_path(address), :class => "btn btn-mini"%>
      <% end %>
    
      <% if can? :destroy, address %>
        <%= link_to 'x',
        address_path(address),
        :method => :delete,
        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
        :class => 'btn btn-mini btn-danger delete_address' %>
      <% end %>
    </span>
    <div class="address" onclick="window.location.href = '<%= "/#{@user.name}/address/#{index+1}"%>'; return false;">
      <strong><p><%= address.label unless address.label.blank? %></p></strong>
      <span><%= address.street_address %></span>
      <span><%= address.street_address_two %></span><br>
      <span><%= address.city %></span>
      <span><%= address.state %></span><br>
      <span><%= address.country %></span>
      <span><%= address.zipcode %></span><br>
      <br>
      <% unless address.phones.empty? %>
        <strong>Phone Numbers</strong>
        <% address.phones.each do |phone| %>
          <p><span>+</span> <%= phone.number %></p>
        <% end %>
      <% end %>
      
      <% unless address.faxs.empty? %>
        <strong>Fax:</strong>
        <% address.faxs.each do |fax| %>
          <p><span>+</span> <%= fax.number %></p>
        <% end %>
      <% end %>
      
      <% unless address.emails.empty? %>
        <strong>Emails:</strong>
        <% address.emails.each do |email| %>
          <p><%= link_to email.email, "mailto:#{email.email}" %></p>
        <% end %>
      <% end %>
    </div>
  </div>

  <% end %>
<% end %>


<br>
<br>
<div style="clear:both;"></div>

<% unless @user.contact_form.blank?  %>
   <%= render 'addresses/contact_form' %>
 <% end %>

app/views/addresses/new.html.erb
<%- model_class = Address -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/addresses/show.html.erb
<%- model_class = Address -%>
<div class="page-header">
   <h1><%= "#{@user.company_name} " %><small><%= link_to "(#{@user.company_url})", @user.company_url, :target => "_blank" %></small></h1>
</div>
            
<div class="map-region">
  
  <div class="tabbable">
    
    
    <div id="map_canvas" style="width:60%; height:500px; background-color: #fff;" class="well pull-left"></div>
    
         
    <div class="tab-content pull-left" style="width: 35%; height: 100%; margin: 0 5px;">
         <ul class="nav nav-pills">
           <li class="active"><%= link_to "Address", "#mapTab1", "data-toggle" => 'tab', :onclick => "initialize(); return true;" %></li>
           <li class=""><%#= link_to "Enlarge", "#"  %></li>
           <li class=""><%= link_to "Directions", "#mapTab2", "data-toggle" => 'tab', :onclick => "calcRoute(); return true;" %></li>
           <li class=""><%= link_to "Nearby Landmarks", "#mapTab3", "data-toggle" => 'tab' %></li>

         </ul>
        <div class="tab-pane active" id="mapTab1">
          <strong><p><%= @address.label.blank? ? "Address" : @address.label %>:</p></strong>
          
          <dl class="dl-vertical">
            <dd><%= @address.street_address %></dd>
            <dd><%= @address.street_address_two %>, </dd>
            <dd><%= @address.city %>, <%= @address.state %></dd>
            <dd><%= @address.country %> - <%= @address.zipcode %></dd> <br>
            
            <% unless @address.phones.empty? %>
              <strong>Phone Numbers</strong>
              <% @address.phones.each do |phone| %>
                <dd><span>+</span> <%= phone.number %></dd>
              <% end %>
            <% end %>
            
            <% unless @address.faxs.empty? %>
              <strong>Fax:</strong>
              <% @address.faxs.each do |fax| %>
                <dd><span>+</span> <%= fax.number %></dd>
              <% end %>
            <% end %>
            
            <% unless @address.emails.empty? %>
              <strong>Emails:</strong>
              <% @address.emails.each do |email| %>
                <dd><%= link_to email.email, "mailto:#{email.email}" %></dd>
              <% end %>
            <% end %>
            
          </dl>
          
        </div>
      
        <div class="tab-pane" id="mapTab2">
          <h4>Directions</h4>
          <div id="search_location">
            <input name="start" id="start" class="input-xlarge muted" placeholder="Where are you coming from?" type="text" size="30" autocomplete="off">
            <%#= link_to "Search", "#", :class => "btn btn-primary", :onclick => "calcRoute(); return false;"%>
          </div>
          <div class="alert hide" id="searchResultError">No places found</div>
          <div id="directionsPanel" style="overflow-y: scroll; height: 400px; margin-top: 10px;"></div>
        </div>
        
        <div class="tab-pane" id="mapTab3">
          <h4>Landmarks</h4>
        </div>
        
    </div>
      
    <div class="clearfix"></div>
  </div>
</div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              addresses_path, :class => 'btn'  %>
  
  <% if can? :update, @address %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_address_path(@address), :class => 'btn' %>
  <% end %>
  
  <% if can? :destroy, @address %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              address_path(@address),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  <% end %>
</div>



<script type="text/javascript">
   var directionsDisplay;
   var map; 
   var directionsService;
   var stepDisplay;
   var marker;
</script>
   
<script type="text/javascript">

  function initialize() {
    
    var myLatlng = new google.maps.LatLng(<%= @address.latitude %>, <%= @address.longitude %>) ;
    var mapOptions = {
      center: myLatlng,
      zoom: 15,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    
    var map = new google.maps.Map(document.getElementById("map_canvas"),
        mapOptions);
        
    marker = new google.maps.Marker({
      position: myLatlng,
      title:"My Location",
      //icon: icon,
      animation: google.maps.Animation.DROP,
    });
    
    var rendererOptions = {
      draggable: true
    };
    directionsDisplay = new google.maps.DirectionsRenderer(rendererOptions);

    // To add the marker to the map, call setMap();
    marker.setMap(map);
    directionsDisplay.setMap(map);
    directionsDisplay.setPanel(document.getElementById("directionsPanel"));
    
    var defaultBounds = new google.maps.LatLngBounds(myLatlng);

    var input = document.getElementById('start');
    var options = {
      bounds: defaultBounds,
      types: ['establishment']
    };

    autocomplete = new google.maps.places.Autocomplete(input, options);
    autocomplete.bindTo('bounds', map);
    //autocomplete.setBounds(bounds);
    google.maps.event.addListener(autocomplete, 'place_changed', function() {
      var place = autocomplete.getPlace();
      if (!place.geometry) {
        // Inform the user that a place was not found and return.
        $("#searchResultError").show();
        return;
      }
      $("#searchResultError").hide();
      calcRoute();
    });
  }
</script>

<script>
  function loadScript() {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src = "http://maps.googleapis.com/maps/api/js?key=AIzaSyAiWC6EU28mQk9du90WHXUQTSTaE48FlFw&libraries=places&sensor=false&callback=initialize";
    document.body.appendChild(script);
  }
  window.onload = loadScript;  
</script>


<script type="text/javascript">

  function calcRoute() {
    var start = document.getElementById("start").value;
    if (start){
      marker.setMap(null);
      var directionsService = new google.maps.DirectionsService();
      var end = new google.maps.LatLng(<%= @address.latitude %>, <%= @address.longitude %>);
      var request = {
        origin:start,
        destination:end,
        travelMode: google.maps.TravelMode.DRIVING
      };
      document.getElementById("directionsPanel").innerHTML = "";
      directionsService.route(request, function(response, status) {
        if (status == google.maps.DirectionsStatus.OK) {
          directionsDisplay.setDirections(response);
        }
      });
    }
  }
</script>